# Generated by Django 5.0.3 on 2024-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='attack',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=4, verbose_name='Сила атаки'),
        ),
        migrations.AddField(
            model_name='products',
            name='defense',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Очки защита'),
        ),
        migrations.AddField(
            model_name='products',
            name='health',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=4, verbose_name='Очки жизни'),
        ),
    ]
