# Generated by Django 5.0.3 on 2024-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_products_attack_products_defense_products_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='defense',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Очки защиты'),
        ),
    ]
