# Generated by Django 5.0.3 on 2024-03-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0002_remove_carddeck_set_of_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardset',
            name='cards_in_set',
        ),
        migrations.AddField(
            model_name='carddeck',
            name='set_of_cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card_decks.cardset', verbose_name='Набор карт'),
        ),
    ]
