# Generated by Django 5.0.3 on 2024-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0003_remove_cardset_cards_in_set_carddeck_set_of_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddeck',
            name='set_of_cards',
        ),
        migrations.AddField(
            model_name='cardset',
            name='cards_in_set',
            field=models.ManyToManyField(null=True, related_name='cards_in_set', to='card_decks.carddeck', verbose_name='Карточки в наборе'),
        ),
    ]
