# Generated by Django 5.0.3 on 2024-03-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0004_remove_carddeck_set_of_cards_cardset_cards_in_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSet',
        ),
    ]
