# Generated by Django 5.0.3 on 2024-04-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0006_cardset'),
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardset',
            name='cards',
        ),
        migrations.AddField(
            model_name='cardset',
            name='card',
            field=models.ManyToManyField(null=True, related_name='card', to='card_decks.carddeck', verbose_name='Карточки в наборе'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания колоды')),
                ('active', models.BooleanField(default=False, verbose_name='Активная колоды')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Колода карт версия 2',
                'verbose_name_plural': 'Колоды карт версия 2',
                'db_table': 'set',
            },
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cards.products', verbose_name='Продукт')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_decks.set', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Проданный товар',
                'verbose_name_plural': 'Проданные товары',
                'db_table': 'set_item',
            },
        ),
    ]
