# Generated by Django 5.0.3 on 2024-04-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0007_remove_cardset_cards_cardset_card_set_setitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'Набор карт версия 2', 'verbose_name_plural': 'Наборы карт версия 2'},
        ),
        migrations.AlterModelOptions(
            name='setitem',
            options={'verbose_name': 'Карточка в наборе (версия 2)', 'verbose_name_plural': 'Карточки в наборе (версия 2)'},
        ),
        migrations.AlterField(
            model_name='setitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='card_decks.carddeck', verbose_name='Карточка в наборе 2'),
        ),
    ]
