# Generated by Django 5.0.3 on 2024-04-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0008_alter_set_options_alter_setitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setitem',
            name='name',
        ),
    ]
