# Generated by Django 5.0.3 on 2024-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0009_remove_setitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setitem',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
