# Generated by Django 5.0.3 on 2024-04-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0011_remove_setitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='card_decks.carddeck', verbose_name='Пользователь'),
        ),
    ]
