# Generated by Django 5.0.3 on 2024-04-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_decks', '0013_alter_set_user_alter_setitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSet',
        ),
    ]
