# Generated by Django 5.0.3 on 2024-04-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Sphere'), ('2', 'Box'), ('3', 'Cylinder')], max_length=1)),
                ('color', models.CharField(help_text='hex', max_length=7)),
            ],
        ),
    ]
